--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Endermanbugzjfc/FormInteractionFix
build-by-default: true
branches:
- poggit
projects:
  FormInteractionFix:
    path: ""
    libs:
      - src: sof3/await-generator/await-generator
        version: ^3.4.3
      - src: sof3/await-std/await-std
        version: ^0.2.0
    icon: assets/icon.png
...
