name: FormInteractionFix
author: Endermanbugzjfc
api: 4.0.0
main: Endermanbugzjfc\FormInteractionFix\Loader
website: https://github.com/Endermanbugzjfc/FormInteractionFix

# version: generated
version: 1.0.0
