name: CI

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [8.1]
    steps:
      - name: Build and prepare PHP cache
        uses: pmmp/setup-php-action@589cc43fddede20c8b0469828431d747fb1a1145
        with:
          php-version: ${{ matrix.php }}
          install-path: "../bin"
          pm-version-major: 5

  typo:
    name: Typo Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: typos-action
        # You may pin to the exact commit or the version.
        # uses: crate-ci/typos@592b36d23c62cb378f6097a292bc902ee73f93ef
        uses: crate-ci/typos@v1.0.4
#         with:
          # Files or patterns to check
#           files: # optional
          # Comma separated list of extend identifiers, like someone's name
#           extend_identifiers: # optional
          # Comma separated list of extend words.
#           extend_words: # optional
          # Ignore implicit configuration files
#           isolated: # optional
          # Use a custom config file.
          #           config: # optional

  phar:
    name: Build PHAR
    permissions:
      contents: write
    needs: [build-php]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [8.1]
    steps:
      - uses: actions/checkout@v3
      - name: Complete plugin manifest with release tag
        if: github.event_name == 'release'
        run: |
          echo "version: ${{ github.ref }}" >> plugin.yml
      - name: Complete plugin manifest with commit SHA
        if: github.event_name != 'release'
        run: |
          echo "version: ${{ github.sha }}" >> plugin.yml
      - name: PSR-420
        run: |
          mkdir "${{ github.repository_owner }}"
          mv src "${{ github.repository }}" # This context contanis both owner and repo name. Example: Endermanbugzjfc/FormInteractionFix
          mkdir src
          mv "${{ github.repository_owner }}" src
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        if: github.event_name == 'release'
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Push to Poggit branch
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        if: steps.import_gpg.outputs
        with:
          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          commit: -s # GPG-signoff.

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "version: ${{ github.sha }}"

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          new_branch: poggit

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: exitAtEnd
      - uses: pmmp/setup-php-action@589cc43fddede20c8b0469828431d747fb1a1145
        with:
          php-version: ${{ matrix.php }}
          install-path: "../bin"
          pm-version-major: 5
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php
      - run: composer install
      - run: composer all
      - name: Rename artifact
        run: mv hack/output.phar hack/${{ github.event.repository.name }}.phar
      - uses: actions/upload-artifact@v3
        if: github.event_name != 'release'
        with:
          name: ${{ github.event.repository.name }}
          path: hack/${{ github.event.repository.name }}.phar
          retention-days: 1 # default 90.
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  # SEC VUL!

  # sftp:
  #   name: Sync PHAR to a private server
  #   needs: [phar]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: ${{ github.event.repository.name }}
  #         path: ./download
  #     - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  #       with:
  #           username: ${{ secrets.FTP_USERNAME }}
  #           server: ${{ secrets.FTP_SERVER }}
  #           port: ${{ secrets.FTP_PORT }}
  #           local_path: './download/${{ github.event.repository.name }}.phar'
  #           remote_path: 'plugins/${{ github.event.repository.name }}.phar'
  #           sftp_only: true
  #           password: ${{ secrets.FTP_PASSWORD }}
  #           delete_remote_files: 1
  #     - if: failure()
  #       run: |
  #         tree ./download
  #         stat ./download/${{ github.event.repository.name }}.phar

  # SEC VUL!

  test:
    name: Integrated test with Docker
    needs: [phar]
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    strategy:
      matrix:
        pm: [4, 4.0.0]
        container-prefix: [form-interaction-fix]
    steps:
      - name: Checkout for IntegratedTest.php
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: /home/runner/plugins
      - name: Docker create and run
        run: >
          docker rm ${{ matrix.container-prefix}}-pocketmine || true;
          docker create --name ${{ matrix.container-prefix}}-pocketmine
          -u root
          pmmp/pocketmine-mp:${{ matrix.pm }}
          start-pocketmine --debug.level=2 --auto-report.enabled=0;

          wget -O /home/runner/plugins/FakePlayer.phar https://poggit.pmmp.io/r/181430/FakePlayer_dev-59.phar;
          docker cp /home/runner/plugins/ ${{ matrix.container-prefix }}-pocketmine:/;
          docker cp IntegratedTest.php ${{ matrix.container-prefix }}-pocketmine:/plugins/IntegratedTest.php;

          docker start -ia ${{ matrix.container-prefix }}-pocketmine;
# https://discord.com/channels/373199722573201408/480650036972224513/1038057748170035260
